name: Score Card
on:
  pull_request:
    branches: [master]

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - run: docker run -e GITHUB_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }} gcr.io/openssf/scorecard:stable --show-details --repo=${{ github.repository }}

        