on:
  pull_request:
    branches: [master]
jobs:
  container:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    container: gcr.io/openssf/scorecard:stable
    steps:
      - run: scorecard --repo=https://github.com/ZupIT/beagle-examples
        